services:
  - type: web
    name: project-city
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: TWITTER_QUERY
        value: "#CITYHamirpur -is:retweet"
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: "5500"