services:
  - type: web
    name: project-city
    runtime: node
    rootDir: backend
    buildCommand: npm install && pip install -r ../nlp_pipeline/requirements.txt
    startCommand: node server.js
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: TWITTER_QUERY
        value: "#CITYHamirpur -is:retweet"
      - key: PORT
        value: "5500"
